### ISSUE TITLE
Send as attachment with commas

### ISSUE THREAD

**Issue by forcenzw** [jankeirse/tvhgooglemapi#38]
Hello,

Any mailto attachments with filenames that have a comma in them trimmed when attached to Google Mail.  In example: "Smith, Joseph.doc" is now changed to "Smith" with no file extension.  

Looks like a quick correction for a simple problem.  Thanks!

**Comment by tedlwsn** [comment]
We have had that issue with Microsoft Office programs as well. We use a program called Laserfiche and the when there is a comma in the file name it completely breaks the Google MAPI. It gives us the MAPI_E_LOGON_FAILURE error, which is the same error as when someone tries to send a file over 25MB.

The only work around is to rename the file and remove the comma. Then everything is fine. But in our Laserfiche setup we have tens of thousands of documents with commas in their names. So its kind of a pain to do that every single time 

The Google MAPI is a great program, and it really helps out the users who've we've had testing it but this seems to be its only major draw back for us.

**Comment by jankeirse** [comment]
If someone wants to fix this, it's very easy: The Drafter.java file contains a couple of calls like .withValueSeparator(',') 
these have to be removed from the line they are in to fix this. 
I'll eventually do it, but we also call gmaildrafter.jar directly internally and I'll have to change that first because we rely on it before I can spent time on a new release.

**Comment by dfoley** [comment]
So did you eventually do this easy fix?

**Comment by jankeirse** [comment]
I'm afraid I didn't, no time so far.
