### ISSUE TITLE
Invalid Login, Please Try Again!

### ISSUE THREAD

**Issue by danpitman** [jankeirse/tvhgooglemapi#46]
I am using Google Apps for Education

If i use my account to login it accepts fine and adds into the Gmail compose window

If i use any other user in my Google Apps Domain i get the above error message, even other admins!

I have made sure "Use Less secure apps" is enabled and IMAP is enabled in the account i am trying, but still the same message, any help with this?

**Comment by jankeirse** [comment]
This may also help: https://support.google.com/accounts/answer/6009563?vid=1-635790400077101136-2917816429

**Comment by lennartbenoot** [comment]
Hi There,
Did you manage to solve this issue? We encounter this issue with some of the accounts that make use of tvhgooglemapi, but no problem with others. 
We have checked the above link, as well as this https://support.google.com/mail/answer/78754?hl=en
but none of the proposed solutions seems to work.

Help much appreciated.

**Comment by jankeirse** [comment]
We had a similar problem with 1 user in another domain, everything set correctly but the login kept being refused. Wait a few hours and try again solved it in our case.

**Comment by BradGough123** [comment]
danpitman Thanks so much for opening this discussion. I'm using Google Apps for Work and kept receiving this error where i though it was due to having a @organistation address instead of @googlemail etc. Turns out i just had to enable IMAP in the Google Admin Settings. 

Thanks a bunch and for anyone else struggling with this error:

- Check less secure apps is enabled
- Check IMAP is enabled

I was going through all sorts of forums and even tried Affixa at one point so glad i found this post. Also for those that don't know Affixa maybe free but if you are part of an organisation you must buy a license to use it which is why I didn't keep is as the permanent solution.

**Comment by jankeirse** [comment]
When we wrote tvhgooglemapi it had it's own interface for composing email, which we didn't want. Add to that the price for a large domain and we decided to make something that works for us the way we want instead. 
I just had a look at the Affixa website and apparently they now also upload a draft so that you can use the gmail interface just like when starting a mail from your browser. 
That basically results in 3 options: 
- use my free tool which works for basic cases, but sees little development and has a couple of documented issues you currently have to live with (most importantly, the lack of UTF-8 support) 
- use my free tool and pay or otherwise motivate a skilled developer to fix the problems that affect you, you may also want to have it changed to the new Gmail HTTPS API while doing so  (sorry, I'm NOT available for hire myself)
- pay for Affixa (assuming it works fine now, I have not evaluated it for years, reading their website it looks like it is a realistic option)

**Comment by BradGough123** [comment]
Hi jankeirse out of the 3 options I'm happy with the first in my case. I personally haven't come across any issues with using it yet is there any other issues that i should be aware of (apart from the lack of UTF-8 support) as i've used tvhgooglemapi as the solution at work as we have just gone Google but we are still using Word, Excel so this allows us to send as an attachment in Gmail instead of Outlook. Again great program that I am happy to help support if they need me.

**Comment by jankeirse** [comment]
All known issues are listed on github. The UTF-8 issue is more relevant for languages with accented characters (é, à,...) but hardly affects people only using English. 
For what it is worth, I am certain that one and have very good reason to believe that multiple large multinationals are using it in production so there's probably not much to worry about if the listed problems on github don't affect you (or you can live with them.)

**Comment by BradGough123** [comment]
Great thank you sounds like its the perfect tool for us :)

**Comment by Travisimoe** [comment]
When installing and trying to login, Google Apps denies login, requiring the "less secure apps" be allowed.  Is there any development plans to address that within the product so as to not have to enable the "less secure app" door within the organization?  Thanks!

**Comment by jankeirse** [comment]
No one I am aware of has plans to solve this. It can be solved, but I certainly don't have time to do so and I am not aware of anyone else who does.

**Comment by BradGough123** [comment]
Why am I attached to this email? I went to use tvhgooglemapi for a solution
within my organisation a couple months ago but can't remember signing up
for anything that would include my email address.

Thanks,

Brad

**Comment by jankeirse** [comment]
@BradGough123  Github automatically subscribes you to an issue you comment on. You commented the first time on march the first. If you want to stop the notifications you can go to https://github.com/jankeirse/tvhgooglemapi/issues/46 and click the unsubscribe button on the right, towards the bottom of page. You can also change Githubs behaviour to stop the automatic watching if you want at https://github.com/settings/notifications .
