### ISSUE TITLE
Use tokens rather than password auth

### ISSUE THREAD

**Issue by MintPaw** [jankeirse/tvhgooglemapi#54]
Is there a reason that it's not possible to use API tokens rather and usename/password storage? I'm working at a business that has migrated from Exchange to Gmail and and would like Gmail to be mapi default, but storing passwords on disk isn't really an option.

**Comment by jankeirse** [comment]
Honest answer:
- Because nobody bothered to implement it.
- I personally never bothered because I don't see how it is significantly less insecure than storing an application specific password: the tokens still have to be stored locally and allow reading and sending mail just as much, not only that, they also give many people a false sense of security, because they think it is somehow less insecure than storing an application specific password. While I see how oauth can be used to secure communication between backend servers of different entities, where access to the secrets is limited to the server administrators, I simply don't have the arrogance to pretend I can secure this on the client side (you somehow have to store secrets on the client computer, the only way I know of doing this is letting the user generate it's own secret in the developer console like gam does (https://github.com/jay0lee/GAM/wiki) and I'm not convinced this provides a security advantage over the current implementation. You have to type the password every time if you want to be safe and I don't pretend otherwise. (Note that I'm not pretending storing passwords locally is secure, i'm saying storing tokens that provide essentially the same capabilities is equally insecure and forcing tokens no longer gives you the capability of not storing the secret.) 

That being said, you are off course welcome to implement this or get it implemented 
- If you want to implement this or pay someone to do so I will look at your patch if it implements https://github.com/jankeirse/tvhgooglemapi/issues/33 instead of imap/smtp because that would be a desireable improvement. (Or even better, implement it within Google Chrome/Chromium, where it really ought to be.) 
- If you do implement it on imap/smtp, you'd best fork because I don't really want to be responsible for maintaining a client side installed application with oauth (mainly because of this: https://hueniverse.com/2012/07/26/oauth-2-0-and-the-road-to-hell/ ), however I am prepared to link to such fork if I don't see obvious glitches.

**Comment by MintPaw** [comment]
It would be much safer in a few key ways, if a full access API key should fall into the wrong hands it can be revoked and not be used to steal all Google related accounts, but in reality you likely wouldn't create create a full access key. All this application does is create drafts and link to them right? Then the API key generated would only need the "auth/gmail.compose" permission.

I'll look into an implementation, thank you for the advice.
