### ISSUE TITLE
PDF names have the full path in it

### ISSUE THREAD

**Issue by arouthier** [jankeirse/tvhgooglemapi#56]
Hi,

I'm not sure it is related to your software, when i generate an email with my clients software (with a PDF inside), the pdf file's name is very long : 

C__Users_username_AppData_Local_Temp_BO123732.pdf

When we do the same operation in outlook, the pdf in attached file is only BO123732.pdf

Is there something i can do to fix that?

Thanks for your help!

Regards

**Comment by jankeirse** [comment]
The reason is that the calling client sets lpszFileName ( https://msdn.microsoft.com/en-us/library/windows/desktop/dd296737(v=vs.85).aspx ) to the full pathname (C:\Users\username\AppData\Local\Temp\BO123732.pdf instead of BO123732.pdf like most applications do. The file is therefore attached with the full filename (as requested really.) and gmail also shows it like that, but replaces : and \ upon downloading because filenames like that can't be stored in Windows. 
There are 2 options:
- fix the calling application
- modify Drafter.java to handle this, strictly speaking that would be introducing a bug since it no longer uses the name it was provided as input, but since major other mail clients do the same thing and a file can't contain backslashes on the platforms that are supported by this application that is probably an acceptable bug.

**Comment by arouthier** [comment]
Hi Jan,

thanks for your answer, i'll check that with my client!

We Really appreciate your time.

Best Regards





*Alexis Routhier*

*Intégrateur logiciel / **Software integrator*


T  1-418-956-5922 / 1-514-266-9774

                  <http://www.gestion-bsp.com>
*__________________________________________________________________*





    2750, rue Einstein, bureau 320, Québec (Qc) G1P 4R1

1, Place Ville Marie, bureau 2901, Montréal (Qc) H3B 0E9



2016-07-22 11:21 GMT-04:00 Jan Keirse <notifications@github.com>:
